name: socratica
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  file_picker: ^8.1.2
  file_saver: ^0.2.14
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  get: ^4.6.6
  http: ^1.2.2
  flutter_markdown: ^0.7.3+1
  lottie: ^3.1.2
  google_generative_ai: ^0.4.6
  image_picker_for_web: ^3.0.5
  livekit_client: ^2.2.5
  logger: ^2.4.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  rive: ^0.13.14
  mesh: ^0.4.1
  deepgram_speech_to_text: ^2.3.2
  record: ^5.1.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/lottie/
    - assets/images/
    - assets/svg/
    - assets/rive/

  fonts:
    - family: Spinnaker
      fonts:
        - asset: fonts/spinnaker/Spinnaker-Regular.ttf
